apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: python-hello-world
  name: python-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      run: python-hello-world
  template:
    metadata:
      labels:
        run: python-hello-world
    spec:
      containers:
        - image: gcr.io/cicd-336010/python-hello-world:latest
          name: python-hello-world
          ports:
            - containerPort: 8080
