apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: node-docker
  name: node-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      run: node-docker
  template:
    metadata:
      labels:
        run: node-docker
    spec:
      containers:
        - image: gcr.io/cicd-336010/node-docker:latest
          name: node-docker
          ports:
            - containerPort: 8080
