apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: docker_example
  name: docker_example
spec:
  replicas: 2
  selector:
    matchLabels:
      run: docker_example
  template:
    metadata:
      labels:
        run: docker_example
    spec:
      containers:
        - image: gcr.io/cicd-336010/docker_example :latest
          name: docker_example
          ports:
            - containerPort: 8080
