kind: Service
apiVersion: v1
metadata:
  name: python-hello-world
spec:
  selector:
    run: python-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
